// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9IZ-gxmNBg8aN9DAUYGHkwx0g9ZeRc1M',
    appId: '1:363628306292:web:a93166638b447ca81dd621',
    messagingSenderId: '363628306292',
    projectId: 'darwaza2026',
    authDomain: 'darwaza2026.firebaseapp.com',
    storageBucket: 'darwaza2026.firebasestorage.app',
    measurementId: 'G-C0N6RRT7G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQdwTr7a2agjucx9IetVgSX2fWhx5HgM',
    appId: '1:363628306292:android:9ad5fadc6398daeb1dd621',
    messagingSenderId: '363628306292',
    projectId: 'darwaza2026',
    storageBucket: 'darwaza2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrVWrbtC2hc5UAwzGPoFNmjn1mJyPUfm0',
    appId: '1:363628306292:ios:f79bfe5f1c9f71201dd621',
    messagingSenderId: '363628306292',
    projectId: 'darwaza2026',
    storageBucket: 'darwaza2026.firebasestorage.app',
    iosBundleId: 'com.marwan.darwazapro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrVWrbtC2hc5UAwzGPoFNmjn1mJyPUfm0',
    appId: '1:363628306292:ios:deac75f2e60bdaa21dd621',
    messagingSenderId: '363628306292',
    projectId: 'darwaza2026',
    storageBucket: 'darwaza2026.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9IZ-gxmNBg8aN9DAUYGHkwx0g9ZeRc1M',
    appId: '1:363628306292:web:68b392eeb5ef15fe1dd621',
    messagingSenderId: '363628306292',
    projectId: 'darwaza2026',
    authDomain: 'darwaza2026.firebaseapp.com',
    storageBucket: 'darwaza2026.firebasestorage.app',
    measurementId: 'G-ECGEJMR3C1',
  );
}
